version: '3.0'

services:
  main:
    container_name: app
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    command: npm start
    restart: always


volumes:
  pgdata:
